-- ============================================
-- LuxQuant Terminal — Entry Pullback Alerts
-- ============================================
-- "This setup already ran +25%. Tell me if it comes back to entry."
--
-- Notifications are generated by notification_worker.py
-- (generate_entry_pullback_notifications) into the existing notifications
-- table, type='entry_pullback'. No triggers. Idempotent.
--
-- Apply:  psql "$DATABASE_URL" -f database/migration-entry-alerts.sql
-- ============================================

CREATE TABLE IF NOT EXISTS entry_alerts (
    id            SERIAL PRIMARY KEY,
    user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    signal_id     TEXT NOT NULL,
    pair          TEXT NOT NULL,
    entry         DOUBLE PRECISION NOT NULL,
    -- how close to entry counts as "back in the zone"
    tolerance_pct DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    triggered_at  TIMESTAMPTZ,
    CONSTRAINT entry_alerts_user_signal_uniq UNIQUE (user_id, signal_id)
);

-- The worker only ever scans armed (untriggered) alerts.
CREATE INDEX IF NOT EXISTS idx_entry_alerts_armed
    ON entry_alerts (pair)
    WHERE triggered_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_entry_alerts_user
    ON entry_alerts (user_id);
