// scripts/gen-coins.mjs
// ────────────────────────────────────────────────────────────────
// Regenerates src/content/coins.generated.js from the LIVE signals DB so the
// programmatic /coins/:slug pages always carry fresh track-record numbers.
//
// Runs on the VPS (which has DB access) via psql — no network, deterministic.
// Coin display names/cg-ids are preserved from the existing generated file;
// only the stats are refreshed, and any pair newly crossing the ≥20-signal
// threshold is added (name defaults to its symbol until enriched).
//
// Usage (on the VPS, from frontend-react/):  node scripts/gen-coins.mjs
// Then rebuild:  npm run build
// ────────────────────────────────────────────────────────────────
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, "../src/content/coins.generated.js");

const MIN_SIGNALS = 20;
const CURATED = new Set(["btc","eth","sol","bnb","xrp","ada","doge","avax","link","dot","trx","matic","shib","ltc","uni","atom","xlm","near","arb","op","inj","render","sui","apt"]);
const QUOTES = ["USDT", "USDC", "USD", "BUSD", "FDUSD"];
const symbolOf = (pair) => {
  for (const q of QUOTES) if (pair.endsWith(q) && pair.length > q.length) return pair.slice(0, -q.length);
  return pair;
};
const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

// ── 1. Preserve existing names/cg from the current generated file ──
const nameMap = {}; // slug -> { name, cg }
if (existsSync(OUT)) {
  try {
    const mod = await import(OUT + `?t=${Date.now()}`);
    for (const c of mod.GEN_COINS || []) nameMap[c.slug] = { name: c.name, cg: c.cg };
  } catch (e) {
    console.warn("[gen-coins] could not read existing names:", e.message);
  }
}

// ── 2. Pull fresh per-coin stats from the DB ──
const SQL = `
SELECT pair, count(*) n,
  min(created_at::timestamptz)::date first_call,
  round(100.0*count(*) FILTER (WHERE status IN ('closed_win','tp1','tp2','tp3'))/NULLIF(count(*) FILTER (WHERE status<>'open'),0),1) wr,
  round(avg(peak_pct) FILTER (WHERE peak_pct IS NOT NULL)::numeric,1) avg_peak,
  round(max(peak_pct)::numeric,1) best,
  count(*) FILTER (WHERE status IN ('closed_win','tp1','tp2','tp3')) wins,
  count(*) FILTER (WHERE status<>'open') resolved
FROM signals GROUP BY pair HAVING count(*)>=${MIN_SIGNALS} ORDER BY n DESC;`.replace(/\n/g, " ");

const raw = execSync(
  `sudo -u postgres psql -d luxquant -At -F'\t' -c "${SQL.replace(/"/g, '\\"')}"`,
  { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 }
);

const stats = {};
const gen = [];
const seen = new Set();
for (const line of raw.trim().split("\n")) {
  if (!line) continue;
  const [pair, n, first, wr, avgPeak, best, wins, resolved] = line.split("\t");
  const sym = symbolOf(pair);
  const slug = slugify(sym);
  if (!slug || seen.has(slug)) continue;
  seen.add(slug);
  stats[slug] = {
    n: +n, since: first, wr: wr === "" ? null : +wr,
    avgPeak: avgPeak === "" ? null : +avgPeak, best: best === "" ? null : +best,
    wins: +wins, resolved: +resolved, pair,
  };
  if (CURATED.has(slug)) continue;
  const known = nameMap[slug];
  gen.push({ slug, symbol: sym, name: known?.name || sym, cg: known?.cg ?? null });
}

// ── 3. Write the generated module ──
const header = `// src/content/coins.generated.js — AUTO-GENERATED by scripts/gen-coins.mjs.
// Do not edit by hand. Built from the live LuxQuant signals DB (pairs with
// >=${MIN_SIGNALS} signals). Stats refresh on every regeneration/deploy.
`;
const body =
  header +
  "\nexport const GEN_COINS = " + JSON.stringify(gen) + ";\n" +
  "\nexport const COIN_STATS = " + JSON.stringify(stats) + ";\n";
writeFileSync(OUT, body);
console.log(`[gen-coins] ${gen.length} generated + ${CURATED.size} curated · stats for ${Object.keys(stats).length} slugs · ${(body.length/1024).toFixed(0)}KB`);
