(function(){'use strict';if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init)}else{init()}
function init(){initHeader();initScrollAnimations();initMobileMenu();initSmoothScroll();initHoverEffects();initVideoModal();initCopyButtons();initPricingCurrency()}
function initHeader(){const header=document.getElementById('site-header');if(!header)return;let lastScroll=0;const scrollThreshold=50;window.addEventListener('scroll',()=>{const currentScroll=window.pageYOffset;if(currentScroll>scrollThreshold){header.classList.add('scrolled')}else{header.classList.remove('scrolled')}
lastScroll=currentScroll})}
function initScrollAnimations(){if(typeof gsap==='undefined'){console.warn('GSAP is not loaded. Animations will not work.');const animatedElements=document.querySelectorAll('[data-animate]');animatedElements.forEach(el=>{el.style.opacity='1';el.style.transform='none'});return}
if(typeof ScrollTrigger!=='undefined'){gsap.registerPlugin(ScrollTrigger)}
const animatedElements=document.querySelectorAll('[data-animate]');animatedElements.forEach((element,index)=>{const animationType=element.getAttribute('data-animate');const delay=parseFloat(element.getAttribute('data-delay'))||0;gsap.set(element,{opacity:0,y:animationType==='fade-up'?30:0,x:animationType==='fade-left'?-30:animationType==='fade-right'?30:0,scale:animationType==='scale'?0.9:1});const animation=gsap.to(element,{opacity:1,y:0,x:0,scale:1,duration:0.8,delay:delay,ease:'power3.out'});if(typeof ScrollTrigger!=='undefined'){ScrollTrigger.create({trigger:element,start:'top 85%',animation:animation,toggleActions:'play none none none'})}else{setTimeout(()=>{animation.play()},index*100+delay*1000)}})}
function initMobileMenu(){const toggle=document.getElementById('mobile-menu-toggle');const panel=document.getElementById('mobile-menu-panel');const closeBtn=document.getElementById('mobile-menu-close');if(!toggle||!panel)return;function openPanel(){panel.classList.add('active');document.body.classList.add('menu-open');toggle.setAttribute('aria-expanded','true');toggle.classList.add('active');const spans=toggle.querySelectorAll('span');spans[0].style.transform='rotate(45deg) translate(5px, 5px)';spans[1].style.opacity='0';spans[2].style.transform='rotate(-45deg) translate(7px, -6px)'}
function closePanel(){panel.classList.remove('active');document.body.classList.remove('menu-open');toggle.setAttribute('aria-expanded','false');toggle.classList.remove('active');const spans=toggle.querySelectorAll('span');spans[0].style.transform='none';spans[1].style.opacity='1';spans[2].style.transform='none'}
toggle.addEventListener('click',(e)=>{e.stopPropagation();if(panel.classList.contains('active')){closePanel()}else{openPanel()}});if(closeBtn){closeBtn.addEventListener('click',(e)=>{e.stopPropagation();closePanel()})}
const menuLinks=panel.querySelectorAll('.mobile-nav-menu a');menuLinks.forEach(link=>{link.addEventListener('click',()=>{closePanel()})});document.addEventListener('keydown',(e)=>{if(e.key==='Escape'&&panel.classList.contains('active')){closePanel()}});panel.addEventListener('touchmove',(e)=>{if(panel.classList.contains('active')){e.stopPropagation()}},{passive:!1})}
function initSmoothScroll(){document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){const href=this.getAttribute('href');if(href==='#'||href==='#!')return;const target=document.querySelector(href);if(target){e.preventDefault();const headerHeight=document.getElementById('site-header')?.offsetHeight||72;const targetPosition=target.offsetTop-headerHeight;window.scrollTo({top:targetPosition,behavior:'smooth'});const panel=document.getElementById('mobile-menu-panel');const toggle=document.getElementById('mobile-menu-toggle');if(panel&&panel.classList.contains('active')){panel.classList.remove('active');document.body.classList.remove('menu-open');toggle.setAttribute('aria-expanded','false');toggle.classList.remove('active');const spans=toggle.querySelectorAll('span');spans[0].style.transform='none';spans[1].style.opacity='1';spans[2].style.transform='none'}}})})}
function initHoverEffects(){const cards=document.querySelectorAll('.feature-card, .benefit-card, .blog-card');cards.forEach(card=>{card.addEventListener('mouseenter',function(){if(typeof gsap!=='undefined'){if(!this.classList.contains('blog-card')){gsap.to(this,{scale:1.02,duration:0.3,ease:'power2.out'})}}});card.addEventListener('mouseleave',function(){if(typeof gsap!=='undefined'){if(!this.classList.contains('blog-card')){gsap.to(this,{scale:1,duration:0.3,ease:'power2.out'})}}})});const buttons=document.querySelectorAll('.btn-primary, .btn-secondary');buttons.forEach(button=>{button.addEventListener('mouseenter',function(){if(typeof gsap!=='undefined'){gsap.to(this,{y:-2,duration:0.2,ease:'power2.out'})}});button.addEventListener('mouseleave',function(){if(typeof gsap!=='undefined'){gsap.to(this,{y:0,duration:0.2,ease:'power2.out'})}})})}
function initVideoModal(){const modal=document.getElementById('demo-modal');const demoButton=document.getElementById('demo-button');const closeButtons=document.querySelectorAll('[data-close-modal]');let player=null;if(!modal)return;function initPlyr(){const video=document.getElementById('demo-video');if(!video){console.warn('Video element not found');return}
const source=video.querySelector('source');if(source){console.log('Video source:',source.src);console.log('Video type:',source.type)}
if(typeof Plyr==='undefined'){console.warn('Plyr is not loaded, retrying...');setTimeout(initPlyr,200);return}
if(player){try{player.destroy()}catch(e){console.warn('Error destroying player:',e)}
player=null}
try{player=new Plyr(video,{controls:['play-large','play','progress','current-time','mute','volume','settings','fullscreen'],settings:['quality','speed'],keyboard:{focused:!0,global:!1},tooltips:{controls:!0,seek:!0},autoplay:!1,clickToPlay:!0,loadSprite:!1});player.on('ready',()=>{console.log('Plyr player ready')});player.on('loadeddata',()=>{console.log('Video data loaded')});player.on('error',(error)=>{console.error('Plyr error:',error)});video.addEventListener('error',(e)=>{console.error('Video element error:',e);console.error('Video error details:',video.error)})}catch(error){console.error('Error initializing Plyr:',error)}}
function openModal(){if(modal){modal.classList.add('active');document.body.style.overflow='hidden';setTimeout(()=>{initPlyr()},100)}}
function closeModal(){if(modal){modal.classList.remove('active');document.body.style.overflow='';if(player){player.pause()}}}
if(demoButton){demoButton.addEventListener('click',function(e){e.preventDefault();openModal()})}
closeButtons.forEach(button=>{button.addEventListener('click',function(e){e.preventDefault();closeModal()})});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&modal.classList.contains('active')){closeModal()}});modal.addEventListener('click',function(e){if(e.target===modal||e.target.classList.contains('video-modal-overlay')){closeModal()}})}
function initCopyButtons(){const copyButtons=document.querySelectorAll('.address-copy-btn');copyButtons.forEach(button=>{button.addEventListener('click',function(){const addressId=this.getAttribute('data-copy');const addressElement=document.getElementById(addressId);if(!addressElement)return;const address=addressElement.textContent.trim();if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(address).then(()=>{showCopyFeedback(this)}).catch(err=>{console.error('Failed to copy:',err);fallbackCopy(address,this)})}else{fallbackCopy(address,this)}})})}
function showCopyFeedback(button){const originalText=button.querySelector('span').textContent;button.classList.add('copied');setTimeout(()=>{button.classList.remove('copied')},2000)}
function fallbackCopy(text,button){const textArea=document.createElement('textarea');textArea.value=text;textArea.style.position='fixed';textArea.style.left='-999999px';textArea.style.top='-999999px';document.body.appendChild(textArea);textArea.focus();textArea.select();try{document.execCommand('copy');showCopyFeedback(button)}catch(err){console.error('Fallback copy failed:',err)}
document.body.removeChild(textArea)}
function initPricingCurrency(){const currencySelect=document.getElementById('pricing-currency-select');if(!currencySelect)return;const currencySymbols={'USD':'$','EUR':'€','GBP':'£','CAD':'C$','AUD':'A$','JPY':'¥','CHF':'Fr'};const exchangeRates={'USD':1,'EUR':0.92,'GBP':0.79,'CAD':1.36,'AUD':1.52,'JPY':149.5,'CHF':0.88};function detectUserCurrency(){try{const locale=navigator.language||navigator.userLanguage;const currencyMap={'en-US':'USD','en-GB':'GBP','fr-FR':'EUR','de-DE':'EUR','es-ES':'EUR','it-IT':'EUR','ja-JP':'JPY','zh-CN':'USD','en-CA':'CAD','en-AU':'AUD','fr-CH':'CHF','de-CH':'CHF'};if(currencyMap[locale]){return currencyMap[locale]}
const lang=locale.split('-')[0];const langMap={'en':'USD','fr':'EUR','de':'EUR','es':'EUR','it':'EUR','ja':'JPY','zh':'USD'};return langMap[lang]||'USD'}catch(e){return'USD'}}
function convertPrice(usdAmount,targetCurrency){const rate=exchangeRates[targetCurrency]||1;const converted=usdAmount*rate;if(targetCurrency==='JPY'){return Math.round(converted)}
return converted.toFixed(2)}
function updatePrices(selectedCurrency){const symbol=currencySymbols[selectedCurrency]||'$';const rate=exchangeRates[selectedCurrency]||1;document.querySelectorAll('.pricing-currency-symbol').forEach(el=>{el.textContent=symbol});document.querySelectorAll('.pricing-amount-small[data-usd]').forEach(el=>{const usdAmount=parseFloat(el.getAttribute('data-usd'));const converted=convertPrice(usdAmount,selectedCurrency);el.textContent=converted});document.querySelectorAll('.pricing-amount-old-small[data-usd]').forEach(el=>{const usdAmount=parseFloat(el.getAttribute('data-usd'));const converted=convertPrice(usdAmount,selectedCurrency);el.textContent=converted});document.querySelectorAll('.pricing-currency-symbol-old').forEach(el=>{el.textContent=symbol})}
const userCurrency=detectUserCurrency();if(currencySelect.querySelector(`option[value="${userCurrency}"]`)){currencySelect.value=userCurrency;updatePrices(userCurrency)}
currencySelect.addEventListener('change',function(){const selectedCurrency=this.value;updatePrices(selectedCurrency);try{localStorage.setItem('pricing-currency',selectedCurrency)}catch(e){}});try{const savedCurrency=localStorage.getItem('pricing-currency');if(savedCurrency&&currencySelect.querySelector(`option[value="${savedCurrency}"]`)){currencySelect.value=savedCurrency;updatePrices(savedCurrency)}}catch(e){}}})()