import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// 1. IMPORT TERJEMAHAN YANG DIPISAH DI SINI
import { orderbookEn, orderbookZh } from './locales/orderbook';
import { calendarEn, calendarZh } from './locales/calendar'; 
import { whaleEn, whaleZh } from './locales/whale'; 
import { tipsEn, tipsZh } from './locales/tips'; 
import { watchlistEn, watchlistZh } from './locales/watchlist'; 
import { userMenuEn, userMenuZh } from './locales/userMenu'; // <-- IMPORT USER MENU

const resources = {
  en: {
    translation: {
      // --- KOSA KATA LAMA ---
      nav: { home: "Home", signals: "Potential Trades", analytics: "Performance", bitcoin: "Bitcoin", markets: "Markets", orderbook: "Order Book", calendar: "Calendar", whale: "Whale Alert", tips: "Tips", watchlist: "Watchlist", admin: "User Management", more: "More", perf: "Perf.", trades: "Trades", btc: "BTC" },
      desc: { orderbook: "Buy/sell wall imbalance", calendar: "Macro economic events", whale: "Large transaction tracker", tips: "Trading guides & education", watchlist: "Your saved coins", admin: "User management" },
      top: { title: "Top Gainer by LuxQuant Algorithm", d1: "1 Day", d7: "1 Week", d30: "1 Month", custom: "Custom", from: "From:", to: "To:", apply: "Apply", total_tp: "Total TP Hits", tp_sub: "signals hit target", unique_pairs: "Unique Pairs", pairs_sub: "different coins", avg_gain: "Avg Gain (Top 5)", gain_sub: "first entry to best TP", avg_dur: "Avg Duration", dur_sub: "first call to last hit", no_tp: "No TP hits found for this period", top_gainers: "Top Gainers by LuxQuant Algorithm Call", called: "Called", first_entry: "First Entry", to_last_tp: "to last TP", no_data: "No data", fastest_hits: "Fastest Hits by LuxQuant Algorithm Call", entry: "Entry", trade_proof: "Trade Proof", view_tg: "View on Telegram ↗", before: "Before (Entry)", fullscreen: "Fullscreen", waiting_ss: "Waiting for entry screenshot...", after: "After", latest: "LATEST", back_img: "Back to Image", interactive: "Interactive Chart", view_full: "View Fullscreen", journey: "Signal Journey", called_sig: "Signal Called", sl_hit: "Stop Loss Hit", hit: "Hit", sig_data: "Signal Data", duration: "Duration", vol_rank: "Volume Rank", risk: "Risk Level", sig_id: "Signal ID", loading: "Loading Signal Data...", failed: "Failed to load signal details", prev: "Prev", next: "Next", signal: "Signal" },
      overview: { title: "Market Overview", error_api: "Global market data temporarily unavailable (API Limit).", retry: "Retry", total_mcap: "Total Market Cap", vol_24h: "24h Volume", btc_dom: "BTC Dominance", active_crypto: "Active Cryptos", sector_perf: "Sector Performance", change_24h: "24h Change", trending: "Trending:", hot: "Hot Narratives", no_gain_sec: "No gaining sectors", cool: "Cooling Down", no_lose_sec: "No losing sectors", indicators: "Market Indicators", eth_dom: "ETH Dominance", stable_dom: "Stablecoin Dom", alt_mcap: "Altcoin MCap", eth_btc: "ETH/BTC", fg_index: "Fear & Greed Index", yesterday: "Yesterday", last_week: "Last Week", trend: "Trend", up: "↑ Up", down: "↓ Down", flat: "→ Flat", deriv_pulse: "Derivatives Pulse", deriv_pending: "Derivatives data pending...", total_oi: "Total Open Interest", funding: "Funding Rates", avg: "avg", pairs_tracked: "pairs tracked", top_gainers_24h: "Top Gainers (24h)", top_losers_24h: "Top Losers (24h)" },
      signals: { title: "Potential Trades", last_7d: "Last 7 Days", signals: "signals", updated: "updated", today: "TODAY", open: "open", closed: "closed", overall_wr: "OVERALL WR", total: "total", this_week: "THIS WEEK", in_view: "signals in view", btc_alert: "BTC DOMINANCE ALERT", dom_index: "Dominance Index", entry_price: "ENTRY PRICE", stop_loss: "STOP LOSS", risk_level: "RISK LEVEL", target_journey: "TARGET JOURNEY", action_plan: "ACTION PLAN", action_desc: "If $BTCDOM is rising, <strong class='text-red-400'>SELL your altcoins</strong>.", action_sub: "BTC absorbs market liquidity. Even if BTC dumps, Altcoins might dump much harder.", risk_mgmt: "RISK MANAGEMENT", risk_desc: "Reduce position sizes drastically. Keep assets in liquid funds (USDT).", recovery: "RECOVERY PLAN", rec_desc: "Buy back when reversal signs appear, or repurpose funds for high-probability setups.", search_pair: "SEARCH PAIR", sort_by: "SORT BY", order: "ORDER", status: "STATUS", all: "All", newest_hit: "Newest Update Hit", loss: "Loss", pair: "PAIR", current_price: "CURRENT PRICE", max_target: "MAX TARGET", mcap: "MCAP", vol: "VOL", last_update: "LAST UPDATE", time: "TIME", called: "Called", update: "Update", get_to_know: "Get to know", just_now: "just now", m_ago: "m ago", h_ago: "h ago", d_ago: "d ago", low: "Low", normal: "Normal", medium: "Medium", high: "High" },
      modal: { chart: "Chart", trade: "Trade", research: "Research", trade_proof: "Trade execution proof & signal progress", before_entry: "Before (Entry)", after: "After", latest: "LATEST", waiting_ss: "Waiting for entry screenshot...", trade_active: "Trade still active", view_full: "View Fullscreen", signal_journey: "Signal Journey", total_duration: "Total Duration", running_active: "Running Active", signal_called: "Signal Called", hit: "Hit", stop_loss_hit: "Stop Loss Hit", open_exchange: "Open Trade on Exchange", summary: "Signal Summary", entry: "Entry", status: "Status", targets_hit: "Targets Hit", max_profit: "Max Profit", research_analytics: "Research & Analytics", deep_dive: "Deep dive into", price: "Price", market_cap: "Market Cap", rank: "Rank", vol_24h: "24h Volume", ath: "ATH", supply: "Supply", website: "Website", no_info: "Coin info not available for", research_links: "Research Links", sentiment: "Sentiment", twitter_feed: "Twitter / X Live Feed", see_what_traders: "See what traders say about", targets: "Targets", stop_loss: "Stop Loss", vol_rank: "Volume Rank", risk_level: "Risk Level", cap: "Cap", vol: "Vol" },
      table: { page: "Page", of: "of", prev: "Prev", next: "Next", no_signals: "No signals found", adjust_filters: "Try adjusting your filters" },
      perf: { title: "Performance Analytics", signals_analyzed: "signals analyzed", all_time: "All Time", ytd: "YTD", days_30: "30 Days", days_7: "7 Days", win_rate: "WIN RATE", closed_trades: "CLOSED TRADES", winners: "WINNERS", losses: "LOSSES", avg_rr: "AVG R:R", not_hit: "NOT HIT", pairs: "pairs", wr_trend: "Win Rate Trend", wr_trend_desc: "Historical performance over time", daily: "Daily", weekly: "Weekly", best: "BEST", worst: "WORST", outcome_dist: "Outcome Distribution", risk_reward: "Risk : Reward", rr_desc: "R:R to max target per level", trades: "trades", risk_analysis: "Risk Level Analysis", risk_desc: "Performance breakdown by signal risk level", low: "low", normal: "normal", high: "high", signals: "SIGNALS", wr_by_risk: "Win Rate by Risk Level", wr_by_risk_desc: "Trend comparison across risk categories", top_pairs: "Top Performing Pairs", top_pairs_desc: "Ranked by win rate (min 5 closed trades)", rank: "#", pair: "PAIR", closed: "CLOSED", wl: "W/L", best_tp: "BEST TP", score: "SCORE", sig_history: "Signal History", total_signals: "total signals", search_pair: "SEARCH PAIR", status: "STATUS", risk: "RISK", sort: "SORT", all_status: "All Status", all_risk: "All Risk", date: "Date", newest: "Newest", entry: "ENTRY", max_target: "MAX TARGET", stop_loss: "STOP LOSS", mcap: "MCAP", not_hit_badge: "NOT HIT" },
      btc: {
        title: "Bitcoin", network: "Bitcoin Network", rank: "Rank", range_24h: "24H RANGE", mcap: "MARKET CAP", vol_24h: "24H VOLUME", dominance: "BTC DOMINANCE", supply: "SUPPLY", circulating: "Circulating", max_supply: "Max Supply", mined: "mined", ath: "ALL-TIME HIGH", from_ath: "from ATH", fg_index: "FEAR & GREED INDEX", sentiment: "Current market sentiment", perp: "Perpetual", live_chart: "LIVE CHART", tech_analysis: "Technical Analysis", tech_desc: "RSI · MACD · Bollinger · EMA", signal_meter: "Signal Meter", buy: "Buy", sell: "Sell", net_health: "Network Health", net_desc: "Hashrate · Fees · Mempool · Difficulty", hashrate: "Hashrate", difficulty: "Difficulty", block_height: "Block Height", mempool: "Mempool", fees: "Fees (sat/vB)", fast: "Fast", min_30: "30min", hr_1: "1hr", eco: "Eco", next_adj: "Next Difficulty Adj.", complete: "complete", blocks_left: "blocks left", onchain: "On-Chain Metrics", onchain_desc: "MVRV · NVT · Addresses · Transactions", mvrv: "MVRV Ratio", nvt: "NVT Signal", active_add: "Active Addresses", daily_tx: "Daily TX", latest_news: "Latest Bitcoin News", news_desc: "CoinDesk · CoinTelegraph · Decrypt", articles: "articles", prev: "Previous", next: "Next", loading_tech: "Loading technical data...", loading_net: "Loading network data...", loading_onchain: "Loading on-chain data...", loading_news: "Loading news...", failed: "Failed to load analysis", retry: "Retry",
        strong_buy: "Strong Buy", strong_sell: "Strong Sell", neutral: "Neutral",
        oversold: "Oversold", overbought: "Overbought", bullish: "Bullish", bearish: "Bearish",
        upper: "Upper", mid: "Mid", lower: "Lower", near_lower: "Near Lower Band", near_upper: "Near Upper Band", middle_range: "Middle Range",
        golden_cross: "Golden Cross", death_cross: "Death Cross",
        overvalued: "Overvalued", undervalued: "Undervalued", fair_value: "Fair Value", normal: "Normal",
        h_ago: "h ago", m_ago: "m ago", d_ago: "d ago", just_now: "just now",
        crypto_news: "Crypto News", open_article: "Open Article"
      },
      markets: {
        title: "Markets", global_overview: "Global Market Overview", live: "Live", total_mcap: "Total Market Cap", vol_24h: "24h Volume", btc_dom: "BTC Dominance", eth_dom: "ETH Dominance", active_coins: "Active Coins", fear_greed: "Fear & Greed", neutral: "Neutral", heatmap: "Market Heatmap", top_50_mcap: "Top 50 by Market Cap", loading_heatmap: "Loading heatmap data...", trending: "Trending Coins", most_searched: "Most searched", loading_trending: "Loading trending...", top_categories: "Top Categories", sectors_perf: "Sectors by performance", loading_categories: "Loading categories...", news_title: "Crypto News", news_sub: "Latest headlines", loading_news: "Loading crypto news...", prev: "← Prev", next: "Next →", derivatives: "Derivatives", funding_sentiment: "Funding & Sentiment", funding_rates: "Funding Rates", most_long: "Most Long", most_short: "Most Short", avg_rate: "Avg Rate:", pairs: "pairs", ls_ratio: "Long/Short Ratio", ratio: "Ratio:", long: "Long", short: "Short", open_interest: "Open Interest", loading_deriv: "Loading derivatives...", liquidations: "Liquidations", recent_closures: "Recent forced closures", total: "Total", longs_liq: "Longs Liq.", shorts_liq: "Shorts Liq.", recent_orders: "Recent Orders", no_liq: "No recent liquidations captured", liq_update: "Data updates every 30 seconds from OKX Futures", loading_liq: "Loading liquidations...", defi_overview: "DeFi Overview", total_tvl: "Total Value Locked", tvl_label: "Total TVL", top_chains: "Top Chains", top_protocols: "Top Protocols", loading_defi: "Loading DeFi data...", macro_stable: "Macro & Stablecoins", macro_sub: "Stablecoin supply & ETF flows", stable_mcap: "Stablecoin MCap", loading_stable: "Loading stablecoins...", etf_flows: "ETF Net Flows", btc_etf: "Bitcoin ETF", eth_etf: "Ethereum ETF", no_data: "No data", etf_key_err: "🔑 ETF data requires SoSoValue API key configuration", loading_etf: "ETF data loading...", aum: "AUM:", all_coins: "All Coins", top_100: "Top 100 by Market Cap", tab_all: "All", tab_gainers: "🟢 Gainers", tab_losers: "🔴 Losers", tab_vol: "📊 Volume", th_coin: "Coin", th_price: "Price", th_mcap: "Market Cap", th_vol: "Volume", showing: "Showing", of: "of", retry: "Retry", just_now: "just now", m_ago: "m ago", h_ago: "h ago", d_ago: "d ago"
      },
      
      // 2. MASUKKAN VARIABEL DI SINI (INGGRIS) - Perhatikan Koma!
      orderbook: orderbookEn,
      calendar: calendarEn,
      whale: whaleEn,
      tips: tipsEn,         
      watchlist: watchlistEn,
      userMenu: userMenuEn // <-- TAMBAHKAN INI

    }
  },
  zh: {
    translation: {
      // --- KOSA KATA LAMA ---
      nav: { home: "主页", signals: "潜在交易", analytics: "表现", bitcoin: "比特币", markets: "市场", orderbook: "订单簿", calendar: "日历", whale: "巨鲸追踪", tips: "提示", watchlist: "自选列表", admin: "用户管理", more: "更多", perf: "表现", trades: "交易", btc: "比特币" },
      desc: { orderbook: "买卖墙不平衡", calendar: "宏观经济事件", whale: "大额交易追踪器", tips: "交易指南与教育", watchlist: "您保存的代币", admin: "用户管理" },
      top: { title: "LuxQuant 算法最高收益", d1: "1 天", d7: "1 周", d30: "1 个月", custom: "自定义", from: "从:", to: "至:", apply: "应用", total_tp: "总止盈次数", tp_sub: "达到目标的信号", unique_pairs: "独立交易对", pairs_sub: "不同的代币", avg_gain: "平均收益 (前五)", gain_sub: "首次入场至最佳止盈", avg_dur: "平均持续时间", dur_sub: "首次呼叫至最后命中", no_tp: "此期间未找到止盈记录", top_gainers: "LuxQuant 算法呼叫的最高收益", called: "呼叫", first_entry: "首次入场", to_last_tp: "至最后止盈", no_data: "无数据", fastest_hits: "LuxQuant 算法呼叫的最快命中", entry: "入场", trade_proof: "交易证明", view_tg: "在 Telegram 上查看 ↗", before: "之前 (入场)", fullscreen: "全屏", waiting_ss: "等待入场截图...", after: "之后", latest: "最新", back_img: "返回图片", interactive: "交互式图表", view_full: "查看全屏", journey: "信号历程", called_sig: "发出信号", sl_hit: "触及止损", hit: "命中", sig_data: "信号数据", duration: "持续时间", vol_rank: "成交量排名", risk: "风险等级", sig_id: "信号 ID", loading: "正在加载信号数据...", failed: "加载信号详情失败", prev: "上一页", next: "下一页", signal: "信号" },
      overview: { title: "市场概览", error_api: "全球市场数据暂时不可用 (API 限制)。", retry: "重试", total_mcap: "总市值", vol_24h: "24小时交易量", btc_dom: "BTC 占比", active_crypto: "活跃加密货币", sector_perf: "板块表现", change_24h: "24小时涨跌", trending: "热门趋势:", hot: "热门叙事", no_gain_sec: "无上涨板块", cool: "降温板块", no_lose_sec: "无下跌板块", indicators: "市场指标", eth_dom: "ETH 占比", stable_dom: "稳定币占比", alt_mcap: "山寨币市值", eth_btc: "ETH/BTC", fg_index: "恐慌与贪婪指数", yesterday: "昨日", last_week: "上周", trend: "趋势", up: "↑ 上涨", down: "↓ 下跌", flat: "→ 平稳", deriv_pulse: "衍生品脉动", deriv_pending: "衍生品数据等待中...", total_oi: "总未平仓合约", funding: "资金费率", avg: "平均", pairs_tracked: "个交易对已追踪", top_gainers_24h: "涨幅榜 (24h)", top_losers_24h: "跌幅榜 (24h)" },
      signals: { title: "潜在交易", last_7d: "过去7天", signals: "个信号", updated: "已更新", today: "今日", open: "未平仓", closed: "已平仓", overall_wr: "总胜率", total: "总计", this_week: "本周", in_view: "视野中的信号", btc_alert: "BTC 占比警报", dom_index: "占比指数", entry_price: "入场价格", stop_loss: "止损价格", risk_level: "风险等级", target_journey: "目标历程", action_plan: "行动计划", action_desc: "如果 $BTCDOM 正在上升，<strong class='text-red-400'>请卖出您的山寨币</strong>。", action_sub: "BTC 会吸收市场流动性。即使 BTC 暴跌，山寨币也可能跌得更惨。", risk_mgmt: "风险管理", risk_desc: "大幅缩减仓位规模。将资产保留在流动资金 (USDT) 中。", recovery: "恢复计划", rec_desc: "当出现反转信号时买回，或将资金用于高概率的交易设置。", search_pair: "搜索交易对", sort_by: "排序方式", order: "顺序", status: "状态", all: "全部", newest_hit: "最新命中", loss: "亏损", pair: "交易对", current_price: "当前价格", max_target: "最高目标", mcap: "市值", vol: "成交量", last_update: "最后更新", time: "时间", called: "发出", update: "更新", get_to_know: "了解更多", just_now: "刚刚", m_ago: "分钟前", h_ago: "小时前", d_ago: "天前", low: "低", normal: "正常", medium: "中", high: "高" },
      modal: { chart: "图表", trade: "交易", research: "研究", trade_proof: "交易执行证明与信号进度", before_entry: "之前 (入场)", after: "之后", latest: "最新", waiting_ss: "等待入场截图...", trade_active: "交易仍在进行中", view_full: "全屏查看", signal_journey: "信号历程", total_duration: "总持续时间", running_active: "运行中", signal_called: "发出信号", hit: "命中", stop_loss_hit: "触及止损", open_exchange: "在交易所打开交易", summary: "信号摘要", entry: "入场", status: "状态", targets_hit: "命中目标", max_profit: "最大利润", research_analytics: "研究与分析", deep_dive: "深入了解", price: "价格", market_cap: "市值", rank: "排名", vol_24h: "24小时交易量", ath: "历史最高价", supply: "供应量", website: "网站", no_info: "没有该代币的信息", research_links: "研究链接", sentiment: "市场情绪", twitter_feed: "Twitter / X 实时动态", see_what_traders: "查看交易员对它的看法", targets: "目标", stop_loss: "止损", vol_rank: "成交量排名", risk_level: "风险等级", cap: "市值", vol: "成交量" },
      table: { page: "页", of: "/", prev: "上一页", next: "下一页", no_signals: "未找到信号", adjust_filters: "尝试调整您的过滤器" },
      perf: { title: "表现分析", signals_analyzed: "个信号已分析", all_time: "全部时间", ytd: "本年迄今", days_30: "30天", days_7: "7天", win_rate: "胜率", closed_trades: "已平仓交易", winners: "盈利", losses: "亏损", avg_rr: "平均盈亏比", not_hit: "未命中", pairs: "个代币", wr_trend: "胜率趋势", wr_trend_desc: "随时间推移的历史表现", daily: "每日", weekly: "每周", best: "最佳", worst: "最差", outcome_dist: "结果分布", risk_reward: "风险与回报", rr_desc: "每个级别的最高目标盈亏比", trades: "笔交易", risk_analysis: "风险等级分析", risk_desc: "按信号风险等级划分的表现", low: "低", normal: "正常", high: "高", signals: "信号数", wr_by_risk: "各风险等级胜率", wr_by_risk_desc: "不同风险类别的趋势比较", top_pairs: "最佳表现代币对", top_pairs_desc: "按胜率排名 (最少 5 笔已平仓交易)", rank: "#", pair: "代币对", closed: "已平仓", wl: "胜/负", best_tp: "最佳止盈", score: "得分", sig_history: "信号历史记录", total_signals: "总信号数", search_pair: "搜索代币对", status: "状态", risk: "风险", sort: "排序", all_status: "所有状态", all_risk: "所有风险", date: "日期", newest: "最新", entry: "入场", max_target: "最高目标", stop_loss: "止损", mcap: "市值", not_hit_badge: "未命中" },
      btc: {
        title: "比特币", network: "比特币网络", rank: "排名", range_24h: "24小时范围", mcap: "市值", vol_24h: "24小时交易量", dominance: "BTC 占比", supply: "供应量", circulating: "流通", max_supply: "最大供应量", mined: "已开采", ath: "历史最高价", from_ath: "距最高点", fg_index: "恐慌与贪婪指数", sentiment: "当前市场情绪", perp: "永续合约", live_chart: "实时图表", tech_analysis: "技术分析", tech_desc: "RSI · MACD · 布林带 · EMA", signal_meter: "信号指示器", buy: "买入", sell: "卖出", net_health: "网络健康", net_desc: "算力 · 费用 · 内存池 · 难度", hashrate: "算力", difficulty: "挖矿难度", block_height: "区块高度", mempool: "内存池", fees: "费用 (sat/vB)", fast: "快", min_30: "30分钟", hr_1: "1小时", eco: "经济", next_adj: "下次难度调整", complete: "完成", blocks_left: "剩余区块", onchain: "链上指标", onchain_desc: "MVRV · NVT · 地址 · 交易", mvrv: "MVRV 比率", nvt: "NVT 信号", active_add: "活跃地址", daily_tx: "每日交易", latest_news: "最新比特币新闻", news_desc: "CoinDesk · CoinTelegraph · Decrypt", articles: "篇文章", prev: "上一页", next: "下一页", loading_tech: "正在加载技术数据...", loading_net: "正在加载网络数据...", loading_onchain: "正在加载链上数据...", loading_news: "正在加载新闻...", failed: "加载分析失败", retry: "重试",
        strong_buy: "强力买入", strong_sell: "强力卖出", neutral: "中立",
        oversold: "超卖", overbought: "超买", bullish: "看涨", bearish: "看跌",
        upper: "上轨", mid: "中轨", lower: "下轨", near_lower: "接近下轨", near_upper: "接近上轨", middle_range: "中间范围",
        golden_cross: "金叉", death_cross: "死叉",
        overvalued: "高估", undervalued: "低估", fair_value: "合理价值", normal: "正常",
        h_ago: "小时前", m_ago: "分钟前", d_ago: "天前", just_now: "刚刚",
        crypto_news: "加密新闻", open_article: "打开文章"
      },
      markets: {
        title: "市场", global_overview: "全球市场概览", live: "实时", total_mcap: "总市值", vol_24h: "24小时交易量", btc_dom: "BTC 占比", eth_dom: "ETH 占比", active_coins: "活跃币种", fear_greed: "恐慌与贪婪", neutral: "中立", heatmap: "市场热力图", top_50_mcap: "市值前 50", loading_heatmap: "正在加载热力图数据...", trending: "热门币种", most_searched: "搜索最多", loading_trending: "正在加载热门...", top_categories: "热门板块", sectors_perf: "各板块表现", loading_categories: "正在加载板块...", news_title: "加密新闻", news_sub: "最新头条", loading_news: "正在加载加密新闻...", prev: "← 上一页", next: "下一页 →", derivatives: "衍生品", funding_sentiment: "资金费率与情绪", funding_rates: "资金费率", most_long: "做多最多", most_short: "做空最多", avg_rate: "平均费率:", pairs: "个交易对", ls_ratio: "多空比", ratio: "比例:", long: "多", short: "空", open_interest: "未平仓合约", loading_deriv: "正在加载衍生品...", liquidations: "爆仓数据", recent_closures: "近期强制平仓", total: "总计", longs_liq: "多头爆仓", shorts_liq: "空头爆仓", recent_orders: "近期订单", no_liq: "近期无爆仓记录", liq_update: "数据每 30 秒从 OKX 合约更新一次", loading_liq: "正在加载爆仓数据...", defi_overview: "DeFi 概览", total_tvl: "总锁仓量 (TVL)", tvl_label: "总 TVL", top_chains: "热门公链", top_protocols: "热门协议", loading_defi: "正在加载 DeFi 数据...", macro_stable: "宏观与稳定币", macro_sub: "稳定币供应与 ETF 资金流向", stable_mcap: "稳定币市值", loading_stable: "正在加载稳定币...", etf_flows: "ETF 净流入", btc_etf: "比特币 ETF", eth_etf: "以太坊 ETF", no_data: "暂无数据", etf_key_err: "🔑 ETF 数据需要配置 SoSoValue API 密钥", loading_etf: "正在加载 ETF 数据...", aum: "资产管理规模 (AUM):", all_coins: "所有币种", top_100: "市值前 100", tab_all: "全部", tab_gainers: "🟢 涨幅榜", tab_losers: "🔴 跌幅榜", tab_vol: "📊 交易量", th_coin: "币种", th_price: "价格", th_mcap: "市值", th_vol: "交易量", showing: "显示", of: "/", retry: "重试", just_now: "刚刚", m_ago: "分钟前", h_ago: "小时前", d_ago: "天前"
      },

      // 3. MASUKKAN VARIABEL DI SINI (MANDARIN) - Perhatikan Koma!
      orderbook: orderbookZh,
      calendar: calendarZh,
      whale: whaleZh,
      tips: tipsZh,         
      watchlist: watchlistZh,
      userMenu: userMenuZh // <-- TAMBAHKAN INI

    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    interpolation: { escapeValue: false }
  });

export default i18n;