// src/components/admin/workspace/WorldMapPanel.jsx
//
// Choropleth for the Location panel. The country lists next to it are precise
// but hard to feel — a reader scanning "ID 18 / VN 3 / US 2" does not see that
// one country is the whole business. Shape does that in one glance.
//
// The map geometry is fetched, not bundled: 173 KB of coordinates would sit in
// the admin chunk for every page load, and only this panel ever needs it. It is
// also cached by the browser after the first open.
import { useEffect, useMemo, useRef, useState } from "react";
import { countryName, flagEmoji, isUnknownCountry } from "./countries";
import * as echarts from "echarts/core";
import { MapChart } from "echarts/charts";
import { TooltipComponent, VisualMapComponent } from "echarts/components";
import { CanvasRenderer } from "echarts/renderers";
import { useChartTokens, inkAlpha } from "../../charts/EChart";

echarts.use([MapChart, TooltipComponent, VisualMapComponent, CanvasRenderer]);

const MAP_NAME = "world-iso2";
const GEO_URL = "/geo/world-iso2.json";
// 16 KB: a small square for each of the 76 countries the 110m world has no
// coastline for. Generated by scripts/build-country-shims.py.
const SHIM_URL = "/geo/country-shims.json";

// Every distinct base+shim combination becomes its own registered map.
const registered = new Set([MAP_NAME]);

// Module-level so a tab switch does not refetch or re-register.
let geoPromise = null;
function ensureWorldMap() {
  if (geoPromise) return geoPromise;
  geoPromise = Promise.all([
    fetch(GEO_URL).then((r) => {
      if (!r.ok) throw new Error(`geo ${r.status}`);
      return r.json();
    }),
    // The shims are an enhancement, not a dependency: if they fail the map
    // still shades every real coastline and the rest falls back to the
    // footnote, exactly as it did before they existed.
    fetch(SHIM_URL)
      .then((r) => (r.ok ? r.json() : { features: [] }))
      .catch(() => ({ features: [] })),
  ])
    .then(([geo, shim]) => {
      echarts.registerMap(MAP_NAME, geo);
      // Keep the label lookup so tooltips can say "Indonesia", not "ID".
      const labels = {};
      const baseNames = new Set();
      for (const f of geo.features || []) {
        labels[f.properties.name] = f.properties.label || f.properties.name;
        baseNames.add(f.properties.name);
      }
      const shims = {};
      for (const f of shim.features || []) {
        shims[f.properties.name] = f;
        labels[f.properties.name] = f.properties.label || f.properties.name;
      }
      return { base: geo, baseNames, shims, labels };
    })
    .catch((e) => {
      geoPromise = null; // let a later mount retry
      throw e;
    });
  return geoPromise;
}

const WorldMapPanel = ({ rows = [], unknown = 0, title = "Signups", height = 340 }) => {
  const hostRef = useRef(null);
  const chartRef = useRef(null);
  const [atlas, setAtlas] = useState(null);
  const labels = atlas?.labels || null;
  const [failed, setFailed] = useState(false);
  const t = useChartTokens();

  useEffect(() => {
    let alive = true;
    ensureWorldMap()
      .then((a) => alive && setAtlas(a))
      .catch(() => alive && setFailed(true));
    return () => {
      alive = false;
    };
  }, []);

  const data = useMemo(
    () =>
      (rows || [])
        .filter((r) => r.country && !isUnknownCountry(r.country))
        .map((r) => ({ name: r.country, value: Number(r.n) || 0 })),
    [rows]
  );

  // Register a map carrying exactly the shims this dataset needs. Merging all
  // 76 into the base would leave a grey square in the ocean for every
  // micro-state we have never heard from.
  const mapName = useMemo(() => {
    if (!atlas) return MAP_NAME;
    const need = data
      .map((d) => d.name)
      .filter((n) => !atlas.baseNames.has(n) && atlas.shims[n])
      .sort();
    if (!need.length) return MAP_NAME;
    const key = `${MAP_NAME}:${need.join(",")}`;
    if (!registered.has(key)) {
      echarts.registerMap(key, {
        type: "FeatureCollection",
        features: [...atlas.base.features, ...need.map((n) => atlas.shims[n])],
      });
      registered.add(key);
    }
    return key;
  }, [atlas, data]);

  const unmapped = useMemo(() => {
    if (!atlas) return [];
    return data.filter(
      (d) => !atlas.baseNames.has(d.name) && !atlas.shims[d.name]
    );
  }, [data, atlas]);

  const max = useMemo(() => Math.max(1, ...data.map((d) => d.value)), [data]);
  const known = useMemo(() => data.reduce((a, d) => a + d.value, 0), [data]);

  useEffect(() => {
    if (!labels || !hostRef.current) return undefined;
    const chart = echarts.init(hostRef.current, null, { renderer: "canvas" });
    chartRef.current = chart;
    const ro = new ResizeObserver(() => chart.resize());
    ro.observe(hostRef.current);
    return () => {
      ro.disconnect();
      chart.dispose();
      chartRef.current = null;
    };
  }, [labels]);

  useEffect(() => {
    const chart = chartRef.current;
    if (!chart || !labels) return;
    chart.setOption(
      {
        tooltip: {
          trigger: "item",
          backgroundColor: t["surface-raised"],
          borderColor: inkAlpha(t, 0.12),
          borderWidth: 1,
          padding: [6, 10],
          textStyle: { color: t.fg, fontSize: 11, fontFamily: "JetBrains Mono, monospace" },
          formatter: (p) => {
            const name = labels[p.name] || countryName(p.name);
            // Scatter items carry [lon, lat, count]; map items carry a number.
            const v = Array.isArray(p.value) ? p.value[2] : p.value;
            if (v == null || Number.isNaN(v)) return `${name}<br/>no data`;
            const share = known ? Math.round((v / known) * 100) : 0;
            const note = atlas?.shims?.[p.name]
              ? "<br/><span style=\"opacity:.6\">block sized for legibility, not to scale</span>"
              : "";
            return `${name}<br/><b>${v}</b> ${title.toLowerCase()} · ${share}% of known${note}`;
          },
        },
        visualMap: {
          // Starts at 1, not 0: a country is either in the data or it is not,
          // so the lowest real value is 1 and it deserves the bottom of the
          // ramp rather than 2.5% of it.
          min: 1,
          max: Math.max(max, 2),
          left: 0,
          bottom: 0,
          orient: "horizontal",
          itemWidth: 10,
          itemHeight: 60,
          calculable: false,
          // Gold ramp — the brand accent, and the only hue already used for
          // "quantity" elsewhere in this workspace. The lightest stop is a
          // clear gold, not a grey: grey is reserved for "no data", and the
          // two must never be confusable.
          inRange: {
            color: ["rgba(240,185,11,0.32)", "rgba(240,185,11,0.65)", "rgb(240,185,11)"],
          },
          textStyle: { color: t["fg-muted"], fontSize: 10 },
          text: [`${max}`, "1"],
        },
        series: [
          {
            type: "map",
            map: mapName,
            roam: false,
            zoom: 1.15,
            center: [15, 25],
            // Countries with no data must not read as zero-with-emphasis;
            // they simply have no data, so they take the plain surface colour.
            itemStyle: {
              areaColor: inkAlpha(t, 0.06),
              borderColor: inkAlpha(t, 0.16),
              borderWidth: 0.5,
            },
            emphasis: {
              label: { show: false },
              itemStyle: { areaColor: "rgb(240,185,11)", borderColor: t.fg },
            },
            select: { disabled: true },
            data,
          },
        ],
      },
      true
    );
  }, [data, mapName, atlas, labels, max, known, t, title]);

  if (failed) {
    return (
      <p className="py-8 text-center text-[12px] text-text-muted">
        Map data could not be loaded. The country lists below are unaffected.
      </p>
    );
  }

  if (!labels) {
    return (
      <div
        className="flex items-center justify-center rounded-xl border border-ink/[0.06] bg-surface-secondary/30"
        style={{ height }}
      >
        <span className="text-[11px] text-text-muted">Loading map…</span>
      </div>
    );
  }

  return (
    <div>
      <div ref={hostRef} style={{ height, width: "100%" }} />
      {unmapped.length > 0 && (
        <p className="mt-1 text-[11px] leading-snug text-text-muted">
          No location on file for:{" "}
          {unmapped
            .map((d) => `${flagEmoji(d.name)} ${countryName(d.name)} ${d.value}`)
            .join(" · ")}
        </p>
      )}
      {unknown > 0 && (
        <p className="mt-1 text-[11px] leading-snug text-text-muted">
          Shaded countries cover{" "}
          <span className="font-semibold tabular-nums text-text-primary">{known}</span> of{" "}
          <span className="font-semibold tabular-nums text-text-primary">{known + unknown}</span>{" "}
          — the other{" "}
          <span className="font-semibold tabular-nums text-loss">{unknown}</span> have no country
          on record, so the map shows where we CAN see, not the whole picture.
        </p>
      )}
    </div>
  );
};

export default WorldMapPanel;
